package top.yumbo.ai.rag.concept;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * 概念版本 (Concept Version)
 *
 * 表示概念的一个历史版本快照
 * (Represents a historical version snapshot of a concept)
 *
 * @author AI Reviewer Team
 * @since 2.0.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ConceptVersion {

    /**
     * 版本ID (Version ID)
     */
    private String versionId;

    /**
     * 概念ID (Concept ID)
     */
    private String conceptId;

    /**
     * 版本号 (Version number)
     */
    private int versionNumber;

    /**
     * 版本内容快照 (Version content snapshot)
     * 保存完整的 ConceptUnit 状态 (Save complete ConceptUnit state)
     */
    private ConceptUnit snapshot;

    /**
     * 变更类型 (Change type)
     */
    @Builder.Default
    private ChangeType changeType = ChangeType.UPDATE;

    /**
     * 变更描述 (Change description)
     */
    private String changeDescription;

    /**
     * 变更原因 (Change reason)
     */
    private String changeReason;

    /**
     * 创建时间 (Creation time)
     */
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * 创建者 (Creator)
     */
    private String createdBy;

    /**
     * 是否是自动生成的版本 (Is auto-generated version)
     */
    @Builder.Default
    private boolean autoGenerated = false;

    /**
     * 版本标签 (Version tags)
     * 如: "stable", "experimental", "deprecated"
     */
    @Builder.Default
    private Map<String, String> tags = new HashMap<>();

    /**
     * 元数据 (Metadata)
     */
    @Builder.Default
    private Map<String, Object> metadata = new HashMap<>();

    /**
     * 变更类型枚举 (Change Type Enum)
     */
    public enum ChangeType {
        /**
         * 创建 (Create)
         */
        CREATE("创建", "Create"),

        /**
         * 更新 (Update)
         */
        UPDATE("更新", "Update"),

        /**
         * 修正 (Fix)
         */
        FIX("修正", "Fix"),

        /**
         * 演化 (Evolution)
         */
        EVOLUTION("演化", "Evolution"),

        /**
         * 合并 (Merge)
         */
        MERGE("合并", "Merge"),

        /**
         * 拆分 (Split)
         */
        SPLIT("拆分", "Split"),

        /**
         * 废弃 (Deprecate)
         */
        DEPRECATE("废弃", "Deprecate");

        private final String chineseName;
        private final String englishName;

        ChangeType(String chineseName, String englishName) {
            this.chineseName = chineseName;
            this.englishName = englishName;
        }

        public String getChineseName() {
            return chineseName;
        }

        public String getEnglishName() {
            return englishName;
        }
    }

    /**
     * 添加标签 (Add tag)
     */
    public void addTag(String key, String value) {
        this.tags.put(key, value);
    }

    /**
     * 检查是否有特定标签 (Check if has specific tag)
     */
    public boolean hasTag(String key) {
        return this.tags.containsKey(key);
    }

    /**
     * 检查是否是稳定版本 (Check if is stable version)
     */
    public boolean isStable() {
        return "stable".equals(tags.get("status"));
    }

    /**
     * 标记为稳定版本 (Mark as stable version)
     */
    public void markAsStable() {
        addTag("status", "stable");
    }
}

